/**
 * TOKENS DE INYECCIÓN DE REPOSITORIOS Y PUERTOS
 * Capa: Infraestructura (Infrastructure Layer)
 */
export const REPOSITORY_TOKENS = {
  CLIENT: Symbol('CLIENT_REPOSITORY'),
  OPERATION: Symbol('OPERATION_REPOSITORY'),
  USER: Symbol('USER_REPOSITORY'),
  REFRESH_TOKEN: Symbol('REFRESH_TOKEN_REPOSITORY'),
  PASSWORD_HASHER: Symbol('PASSWORD_HASHER'),
  TOKEN_SERVICE: Symbol('TOKEN_SERVICE'),
  AUDIT_LOG: Symbol('AUDIT_LOG_REPOSITORY'),
} as const;
